import TopNavbar from '@/components/TopNavbar'
import Head from 'next/head'

import {
    Container,
    Content,
} from 'react-bulma-components'

export default function StandardPage({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavbar />
            <Container className="main" renderAs="main">
                {children}
            </Container>
            <Container
                max
                breakpoint="fullhd"
                textAlign="center"
                className="page-footer"
                renderAs="footer"
            >
                <Content>&copy; TiMalo — 2022</Content>
            </Container>
        </>
    )
}
