/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TAkw9ZCtCWp
 */
import Link from 'next/link'
import { cookies } from 'next/headers'
import { Button } from '@/components/ui/button'
import { ModeToggle } from '@/components/mode-toogle'
import Sidebar from '@/components/dashboard/sidebar'
import SideMenu from '@/components/dashboard/side-menu'
import DashboardPath from '@/components/dashboard/dashboard-path'
import { IconAttributes } from '@kreyolopal/react-ui'
import { redirect } from 'next/navigation'
import { parseCookie } from '@/lib/utils'
import { UserDropdown } from '@/components/dashboard/user-dropdown'

const cookieName = process.env.NEXT_PUBLIC_COOKIE_NAME || 'wabap'

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieValue = cookies().get(cookieName)
  if (cookieValue === undefined) {
    redirect('/login')
  }
  const auth = parseCookie(cookieValue.value)
  if (auth?.session_id === undefined) {
    cookies().delete(cookieName)
    redirect('/login')
  }

  return (
    <div className="grid h-screen w-full lg:grid-cols-[280px_1fr]">
      <Sidebar>
        <SideMenu />
      </Sidebar>
      <div className="flex flex-col">
        <header className="flex h-14 items-center justify-between px-6 bg-gray-100/40 dark:bg-gray-800/40">
          <div className="flex items-center gap-4">
            <Link className="lg:hidden" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="sr-only">Home</span>
            </Link>
            <DashboardPath />
          </div>
          <div className="flex items-center gap-4">
            <UserDropdown token={auth?.session_id as string} />
            <ModeToggle />
            <Button variant="logo">Logout</Button>
          </div>
        </header>
        {children}

        <footer className="flex items-center justify-between px-6 py-4 bg-gray-100/40 dark:bg-gray-800/40">
          <p className="text-sm text-gray-500 dark:text-gray-400">
            © 2024 Kreyolopal. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  )
}

function Package2Icon(props: IconAttributes) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}
