---
# tasks file for firewall
- name: Firewall | install ufw
  apt:
    name: ufw
    state: present
- name: Firewall | Policy
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - {direction: incoming, policy: deny }
    - {direction: outgoing, policy: allow }
- name: Firewall | Ports
  ufw:
    rule: limit
    port: ssh
- name: Firewall | http(s)
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - http
    - https
- name: Firewall | Activate
  ufw: 
    state: enabled