/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7Zyk89nt9tB
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { IconAttributes } from "@/lib/utils"

const FlagGp = (props: IconAttributes) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 80 40"
    {...props}
  >
    <path fill="#078930" d="M0 0h80v40H0z" />
    <path fill="#fff" d="M0 5h80v30H0z" />
    <path fill="#da121a" d="M0 7h80v26H0z" />
    <path
      fill="#fcdd09"
      d="m20 13.5 4.224 13-11.058-8.034h13.669L10.148 26.5z"
    />
  </svg>
)

export function Entry() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1 py-6">
        <div className="container space-y-6 px-4 md:px-6">
          <div className="grid items-start gap-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              <span className="flex items-center gap-2">
                <Button size="icon" variant="outline">
                  <BookmarkIcon className="h-6 w-6" />
                </Button>
                Serendipity
              </span>
            </h1>
            <p className="text-gray-500 dark:text-gray-400">/ˌsɛr(ə)nˈdɪpɪti/</p>
          </div>
          <div className="above-article flex flex-row">
            <article className="gap-2  basis-3/4">
              <section className="definition py-4 border-b-gray-200 border-b-2 dark:bg-inherit dark:border-b-gray-700">

                <div className="grid gap-2">
                  <FlagGp className="w-8 h-4" />
                  <p className="nature text-md text-gray-400 dark:text-gray-600">
                    <span className="font-medium">1. noun</span>
                  </p>
                  <section className="meaning text-xl text-gray-500 dark:text-gray-400 mb-3">

                    <p>
                      The occurrence and development of events by chance in a happy or beneficial way.
                    </p>
                  </section>
                </div>
                <section className="synonyms grid gap-2 mb-2">
                  <h2 className="text-lg font-bold">Synonyms</h2>
                  <ul className="flex flex-wrap gap-2">
                    <li>
                      <Link className="text-sm rounded-lg bg-gray-100 px-2 py-1 dark:bg-gray-800" href="#">
                        Happenstance
                      </Link>
                    </li>
                    <li>
                      <Link className="text-sm rounded-lg bg-gray-100 px-2 py-1 dark:bg-gray-800" href="#">
                        Luck
                      </Link>
                    </li>
                    <li>
                      <Link className="text-sm rounded-lg bg-gray-100 px-2 py-1 dark:bg-gray-800" href="#">
                        Fortune
                      </Link>
                    </li>
                  </ul>
                </section>
                <section className="usage grid gap-2 my-3">
                  <h2 className="text-lg font-bold">Usage</h2>
                  <ul className="grid gap-4 tracking-normal">
                    <li>
                      The discovery was a happy
                      <strong>serendipity</strong>
                      that opened up new possibilities.
                    </li>
                    <li>The word &ldquo;serendipity&rdquo; was coined by Horace Walpole in the 18th century.</li>
                    <li>
                      She always believed that
                      <strong>serendipity</strong>
                      would lead her to her true love.
                    </li>
                  </ul>
                </section>
              </section>

            </article>
            <aside className="hidden md:block  basis-1/4 px-4">
              <div className="sticky top-20">
                <div className="bg-gray-100 dark:bg-gray-800 p-4 rounded-lg">
                  <h3 className="text-lg font-semibold mb-2">See Also</h3>
                  <ul className="space-y-2">
                    <li>
                      <Link className="text-gray-700 dark:text-gray-300 hover:underline" href="#">
                        Coincidence
                      </Link>
                    </li>
                    <li>
                      <Link className="text-gray-700 dark:text-gray-300 hover:underline" href="#">
                        Destiny
                      </Link>
                    </li>
                    <li>
                      <Link className="text-gray-700 dark:text-gray-300 hover:underline" href="#">
                        Fate
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </main>
    </div>
  )
}

function BookmarkIcon(props: IconAttributes) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}

