/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8CrEgdl2Y1u
 */
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function SpellcheckForm() {
  return (
    <div className="w-full max-w-2xl space-y-4">
      <div className="p-4 border border-dashed rounded-lg flex items-center justify-center">
        <form className="w-full space-y-4">
          <div className="grid w-full">
            <Label className="text-base" htmlFor="text">
              Enter your Kreyol text
            </Label>
            <Textarea id="text" placeholder="Enter your Kreyol text here." rows={8} />
          </div>
          <div className="flex w-full items-center space-x-2">
            <Button className="w-[140px]" type="submit">
              Check Spelling
            </Button>
            <Button className="w-[80px]" type="button">
              Clear
            </Button>
          </div>
        </form>
      </div>
      <div className="grid w-full gap-2">
        <Label className="text-base" htmlFor="corrected">
          Corrected text
        </Label>
        <Textarea id="corrected" placeholder="Corrected text" rows={8} />
        <div className="flex w-full justify-between items-center space-x-2">
          <Button className="w-[160px]" type="button">
            Copy to Clipboard
          </Button>
          <div className="flex items-center space-x-1">
            <StarIcon className="w-5 h-5 stroke-primary" />
            <StarIcon className="w-5 h-5 stroke-primary" />
            <StarIcon className="w-5 h-5 stroke-primary" />
            <StarIcon className="w-5 h-5 stroke-primary" />
            <StarIcon className="w-5 h-5 stroke-primary" />
          </div>
        </div>
      </div>
    </div>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
