#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE ROLE ${DB_API_ROLE};
    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_API_ROLE};
    GRANT ALL ON ALL TABLES IN SCHEMA ${DB_SCHEMA} TO ${DB_API_ROLE};
END
