
---
- name: APP SERVER | npm install
  command: 
    cmd: npm install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/server"
  environment:
    NODE_ENV: 'production'
- name: APP DICO | npm install
  command: 
    cmd: npm install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/dico"
  environment:
    NODE_ENV: 'production'

