---
- name: DEPLOY | Create global .env
  template:
    src: env_docker.j2
    dest: "{{ ansistrano_shared_path }}/.env"

- name: DEPLOY | Create API .env (server2)
  template:
    src: env_api.j2
    dest: "{{ ansistrano_shared_path }}/server2/.env"

- name: DEPLOY | Create ADMIN .env
  template:
    src: env_admin.j2
    dest: "{{ ansistrano_shared_path }}/admin/.env"

- name: DEPLOY | Create docker-compose
  template:
    src: compose.j2
    dest: "{{ ansistrano_shared_path }}/docker-compose.yml"
