---
- name: DEPLOY | Create global .env
  template:
    src: env_docker.j2
    dest: "{{ ansistrano_shared_path }}/.env"

- name: DEPLOY | Create API .env
  template:
    src: env_api.j2
    dest: "{{ ansistrano_shared_path }}/server/.env"

- name: DEPLOY | Create ADMIN .env
  template:
    src: env_dico.j2
    dest: "{{ ansistrano_shared_path }}/admin/.env.local"

- name: DEPLOY | Create docker-compose
  template:
    src: compose.j2
    dest: "{{ ansistrano_shared_path }}/docker-compose.yml"
