---
- name: DEPLOY | Create postgres data file
  file:
    path: "{{ ansistrano_shared_path }}/data/db"
    owner: "{{ user }}"
    state: directory

- name: DEPLOY | Create mongodb data file
  file:
    path: "{{ ansistrano_shared_path }}/data/mongodb"
    owner: "{{ user }}"
    state: directory

- name: DEPLOY | Create mongodb keys file
  command: openssl rand -base64 756 > "{{ ansistrano_shared_path }}/keys/keyFile.key"
  args:
    creates: "{{ ansistrano_shared_path }}/keys/keyFile.key"

