---
- name: DEPLOY | Create postgres data file
  file:
    path: "{{ ansistrano_shared_path }}/data/db"
    owner: "{{ user }}"
    state: directory

- name: DEPLOY | Create mongodb data file
  file:
    path: "{{ ansistrano_shared_path }}/data/mongodb"
    owner: "{{ user }}"
    state: directory

- name: DEPLOY | Create mongodb keys directory
  file:
    path: "{{ ansistrano_shared_path }}/keys"
    owner: "{{ user }}"
    state: directory

- name: DEPLOY | create key content
  command: openssl rand -base64 756
  register: mongo_key_file

- name: DEPLOY | Create mongodb keys file
  ansible.builtin.copy:
    content: "{{ mongo_key_file.stdout }}"
    dest: "{{ ansistrano_shared_path }}/keys/keyFile.key"
    owner: "{{ user }}"
    group: wheel
    mode: a+r



