---    
- name: DEPLOY | Create API .env
  template:
    src: api_env.j2
    dest: "{{ ansistrano_shared_path }}/server/.env"

- name: DEPLOY | Create DICO .env
  template:
    src: dico_env.j2
    dest: "{{ ansistrano_shared_path }}/dico/.env.local"
    