---
- name: APP | start api
  command:
    cmd: pm2 start npm --name "api.{{ domain }}" -- start
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/server"

- name: APP | start admin
  command:
    cmd: pm2 start npm --name "admin.{{ domain }}" -- start
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/admin"

- name: APP | saving app list
  command: pm2 save
