---
- name: Déploiement des applicatifs
  hosts: all
  remote_user: '{{ user }}'
  tasks:
    - include_vars:
        file: vars.yml
    - name: DEPLOY |  salts & keys
      set_fact:
        session_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
        api_salt: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
        token_salt: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
        cacheable: yes
    - name: DEPLOY | Set apps port
      set_fact:
        "{{ item.key }}_port": "{{ item.value.port }}"
      loop: "{{  apps | dict2items }}"
    - debug:
        msg: "Api Port '{{ api_port }}'"
#    - include_role:
#        name: ansistrano.deploy
