---
- name: Déploiement des applicatifs
  hosts: all
  gather_facts: true
  remote_user: '{{ user }}'
  tasks:
    - include_vars:
        file: vars_ansistrano.yml
        file: vars.yml

    - include_role:
        name: ansistrano.rollback
