# ansistrano
ansistrano_deploy_from: "{{ playbook_dir }}/../build/"
ansistrano_deploy_to: "/home/{{ user }}/{{ domain }}"
ansistrano_deploy_via: rsync
ansistrano_keep_releases: 3
ansistrano_shared_paths: ["data","keys", "api-server/dico"]
ansistrano_shared_files: [".env", "docker-compose.yml", "api-server/.env"]

ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/tasks/before-setup.yml"
ansistrano_before_update_code_tasks_file: "{{ playbook_dir }}/tasks/before-update-code.yml"
ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/before-symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/after-symlink.yml"
ansistrano_rollback_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/start-apps.yml"
